apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: "myclusteruser"
          - name: POSTGRES_PASSWORD
            value: "12sFFF02Aa"
          - name: POSTGRES_DB
            value: "principal_db"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: customers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: lelodois/customers:1
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: lelodois/orders:3
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  selector:
    app: customers
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30000
  type: NodePort
